// sentencesData.js

// 將題庫資料獨立出來，方便管理與維護。
export const sentencesByLevel = {
    1: [
      { words: ["I", "see", "a", "dog"], chinese: "我看見一隻狗。", hint: "簡單的觀察句" },
      { words: ["The", "sun", "is", "hot"], chinese: "太陽是熱的。", hint: "描述太陽" },
      { words: ["She", "can", "run", "fast"], chinese: "她可以跑得很快。", hint: "描述一種能力" },
      { words: ["He", "has", "a", "red", "car"], chinese: "他有一輛紅色的車。", hint: "描述擁有物" },
      { words: ["We", "like", "to", "play"], chinese: "我們喜歡玩。", hint: "表達喜好" },
      { words: ["The", "cat", "is", "small"], chinese: "這隻貓很小。", hint: "描述動物的大小" },
      { words: ["My", "mom", "is", "nice"], chinese: "我的媽媽人很好。", hint: "描述家庭成員" },
      { words: ["Birds", "can", "fly", "high"], chinese: "鳥可以飛得很高。", hint: "鳥會做什麼？" },
      { words: ["The", "sky", "is", "blue"], chinese: "天空是藍色的。", hint: "描述天空的顏色" },
      { words: ["I", "have", "a", "pen"], chinese: "我有一支筆。", hint: "簡單的所有權陳述" },
      { words: ["Fish", "live", "in", "water"], chinese: "魚住在水裡。", hint: "魚住在哪裡？" },
      { words: ["The", "ball", "is", "round"], chinese: "球是圓的。", hint: "描述形狀" },
      { words: ["He", "can", "read", "a", "book"], chinese: "他會讀一本書。", hint: "一個帶有受詞的動作" },
      { words: ["You", "are", "my", "friend"], chinese: "你是我的朋友。", hint: "描述一種關係" },
      { words: ["The", "grass", "is", "green"], chinese: "草是綠色的。", hint: "描述大自然的顏色" },
      { words: ["I", "eat", "an", "apple"], chinese: "我吃一顆蘋果。", hint: "一個日常動作" },
      { words: ["She", "sings", "a", "song"], chinese: "她唱一首歌。", hint: "一個音樂活動" },
      { words: ["They", "go", "to", "school"], chinese: "他們去上學。", hint: "一個日常慣例" },
      { words: ["The", "moon", "is", "bright"], chinese: "月亮是明亮的。", hint: "描述月亮" },
      { words: ["It", "is", "a", "fun", "game"], chinese: "這是一個有趣的遊戲。", hint: "描述一個活動" }
    ],
    2: [
      { words: ["The", "little", "bird", "sings", "sweetly"], chinese: "小鳥甜美地歌唱。", hint: "描述鳥的歌聲" },
      { words: ["My", "dad", "drives", "a", "big", "truck"], chinese: "我爸爸開一輛大卡車。", hint: "關於家庭成員的交通工具" },
      { words: ["We", "play", "at", "the", "park"], chinese: "我們在公園玩。", hint: "一個玩樂的地點" },
      { words: ["The", "yellow", "bus", "is", "slow"], chinese: "那輛黃色巴士很慢。", hint: "描述一輛車" },
      { words: ["I", "see", "a", "rainbow", "in", "the", "sky"], chinese: "我在天空中看到一道彩虹。", hint: "一種自然現象" },
      { words: ["He", "wears", "a", "blue", "hat"], chinese: "他戴著一頂藍色的帽子。", hint: "描述衣物" },
      { words: ["She", "likes", "to", "eat", "ice", "cream"], chinese: "她喜歡吃冰淇淋。", hint: "一種喜愛的食物" },
      { words: ["The", "dog", "sleeps", "on", "the", "rug"], chinese: "狗睡在地毯上。", hint: "動物睡覺的地方" },
      { words: ["My", "school", "has", "a", "big", "playground"], chinese: "我的學校有一個大操場。", hint: "描述學校的一個地方" },
      { words: ["The", "stars", "shine", "at", "night"], chinese: "星星在夜晚閃耀。", hint: "關於夜空" },
      { words: ["I", "help", "my", "mom", "cook", "dinner"], chinese: "我幫媽媽做晚餐。", hint: "一個有幫助的行為" },
      { words: ["The", "train", "is", "long", "and", "fast"], chinese: "這列火車又長又快。", hint: "描述一列火車" },
      { words: ["She", "draws", "a", "beautiful", "picture"], chinese: "她畫了一幅美麗的圖畫。", hint: "一個藝術活動" },
      { words: ["He", "rides", "his", "bike", "to", "the", "store"], chinese: "他騎他的自行車去商店。", hint: "一個動作和目的地" },
      { words: ["We", "read", "books", "in", "the", "library"], chinese: "我們在圖書館讀書。", hint: "在特定地點的活動" },
      { words: ["The", "flower", "smells", "very", "good"], chinese: "這朵花聞起來很香。", hint: "描述氣味" },
      { words: ["I", "want", "to", "be", "a", "teacher"], chinese: "我想要成為一名老師。", hint: "未來的抱負" },
      { words: ["The", "monkey", "eats", "a", "yellow", "banana"], chinese: "猴子吃一根黃色的香蕉。", hint: "一種動物和牠的食物" },
      { words: ["My", "friend", "lives", "in", "a", "white", "house"], chinese: "我的朋友住在一棟白色的房子裡。", hint: "描述朋友的家" },
      { words: ["It", "is", "cold", "in", "the", "winter"], chinese: "冬天很冷。", hint: "描述季節天氣" }
    ],
    3: [
        { words: ["I", "went", "to", "the", "zoo", "yesterday"], chinese: "我昨天去了動物園。", hint: "一個過去的事件" },
        { words: ["She", "is", "happy", "but", "he", "is", "sad"], chinese: "她很快樂，但他很傷心。", hint: "對比的情緒 (使用 'but')" },
        { words: ["He", "played", "soccer", "with", "his", "friends"], chinese: "他和他的朋友們踢了足球。", hint: "一個過去和他人一起的活動" },
        { words: ["We", "ate", "pizza", "and", "drank", "soda"], chinese: "我們吃了披薩也喝了汽水。", hint: "列出過去的動作 (使用 'and')" },
        { words: ["The", "cat", "jumped", "over", "the", "fence"], chinese: "貓跳過了柵欄。", hint: "一個帶有移動介係詞的動作" },
        { words: ["My", "teacher", "gave", "us", "homework"], chinese: "我的老師給了我們功課。", hint: "一個在學校發生的過去事件" },
        { words: ["They", "watched", "a", "movie", "last", "night"], chinese: "他們昨晚看了一部電影。", hint: "一個過去的休閒活動" },
        { words: ["I", "lost", "my", "keys", "so", "I", "was", "late"], chinese: "我弄丟了鑰匙，所以我遲到了。", hint: "因果關係 (使用 'so')" },
        { words: ["She", "found", "a", "shiny", "coin", "on", "the", "ground"], chinese: "她在地上找到一枚閃亮的硬幣。", hint: "一個過去的發現" },
        { words: ["He", "built", "a", "tall", "sandcastle", "at", "the", "beach"], chinese: "他在沙灘上蓋了一座很高的沙堡。", hint: "一個過去的創造性活動" },
        { words: ["We", "visited", "our", "grandparents", "last", "weekend"], chinese: "我們上週末拜訪了我們的祖父母。", hint: "一個過去的家庭活動" },
        { words: ["The", "dog", "barked", "loudly", "at", "the", "mailman"], chinese: "狗對著郵差大聲地叫。", hint: "用副詞描述過去的動作" },
        { words: ["I", "finished", "my", "book", "and", "felt", "happy"], chinese: "我讀完了我的書，並感到快樂。", hint: "一連串的過去事件" },
        { words: ["She", "wore", "a", "pretty", "dress", "to", "the", "party"], chinese: "她穿了一件漂亮的洋裝去派對。", hint: "描述過去的穿著" },
        { words: ["They", "swam", "in", "the", "cool", "lake"], chinese: "他們在涼爽的湖裡游泳。", hint: "一個過去的休閒活動" },
        { words: ["He", "was", "tired", "because", "he", "woke", "up", "early"], chinese: "他很累，因為他很早就起床了。", hint: "解釋原因 (使用 'because')" },
        { words: ["The", "rain", "stopped", "and", "the", "sun", "came", "out"], chinese: "雨停了，然後太陽出來了。", hint: "天氣的變化 (過去式)" },
        { words: ["I", "wrote", "a", "letter", "to", "my", "cousin"], chinese: "我寫了一封信給我的表親。", hint: "一個過去的溝通活動" },
        { words: ["She", "helped", "her", "brother", "with", "his", "project"], chinese: "她幫助她的弟弟做他的專題。", hint: "一個過去有幫助的行為" },
        { words: ["We", "listened", "to", "music", "in", "the", "car"], chinese: "我們在車上聽音樂。", hint: "一個過去在旅途中的活動" }
    ],
    4: [
        { words: ["I", "will", "visit", "my", "friend", "tomorrow"], chinese: "我明天將會拜訪我的朋友。", hint: "一個未來的計畫" },
        { words: ["She", "will", "be", "a", "doctor", "in", "the", "future"], chinese: "她未來將會成為一位醫生。", hint: "一個未來的職業抱負" },
        { words: ["He", "is", "studying", "because", "he", "has", "a", "test"], chinese: "他正在讀書，因為他有個考試。", hint: "一個行動的原因" },
        { words: ["They", "are", "going", "to", "travel", "to", "Europe"], chinese: "他們將要去歐洲旅行。", hint: "一個未來的旅行計畫 (使用 'going to')" },
        { words: ["If", "it", "is", "sunny", "we", "will", "go", "to", "the", "beach"], chinese: "如果天氣晴朗，我們就去海邊。", hint: "一個條件句" },
        { words: ["We", "will", "have", "a", "party", "next", "Saturday"], chinese: "我們下週六要辦一個派對。", hint: "一個未來的事件" },
        { words: ["He", "was", "hungry", "so", "he", "made", "a", "sandwich"], chinese: "他餓了，所以他做了一個三明治。", hint: "一個感覺導致的結果" },
        { words: ["She", "is", "learning", "how", "to", "play", "the", "guitar"], chinese: "她正在學習如何彈吉他。", hint: "一個正在進行的活動" },
        { words: ["I", "think", "it", "will", "rain", "this", "afternoon"], chinese: "我想今天下午會下雨。", hint: "一個對未來的預測" },
        { words: ["You", "should", "always", "try", "your", "best"], chinese: "你應該永遠盡力而為。", hint: "給予建議" },
        { words: ["He", "will", "probably", "be", "late", "for", "the", "meeting"], chinese: "他開會可能會遲到。", hint: "一個可能的未來結果" },
        { words: ["She", "is", "excited", "because", "it", "is", "her", "birthday"], chinese: "她很興奮，因為今天是她的生日。", hint: "解釋一種情緒" },
        { words: ["They", "will", "build", "a", "new", "house", "next", "year"], chinese: "他們明年要蓋一棟新房子。", hint: "一個未來的建設計畫" },
        { words: ["I", "will", "call", "you", "when", "I", "get", "home"], chinese: "我到家時會打電話給你。", hint: "一個取決於另一件事的未來行動" },
        { words: ["He", "forgot", "his", "umbrella", "so", "he", "got", "wet"], chinese: "他忘了帶傘，所以他淋濕了。", hint: "一個過去行動的後果" },
        { words: ["She", "is", "going", "to", "bake", "cookies", "for", "the", "party"], chinese: "她打算為派對烤餅乾。", hint: "一個未來的意圖" },
        { words: ["We", "must", "finish", "our", "work", "before", "we", "play"], chinese: "我們必須在玩之前完成工作。", hint: "一項義務" },
        { words: ["The", "movie", "will", "start", "in", "ten", "minutes"], chinese: "電影將在十分鐘後開始。", hint: "一個特定的未來時間" },
        { words: ["He", "is", "saving", "money", "to", "buy", "a", "new", "computer"], chinese: "他正在存錢買一台新電腦。", hint: "一個行動的目的" },
        { words: ["If", "you", "study", "hard", "you", "will", "get", "good", "grades"], chinese: "如果你努力學習，你會得到好成績。", hint: "一個條件性的結果" }
    ],
    5: [
        { words: ["The", "quick", "brown", "fox", "jumps", "over", "the", "lazy", "dog"], chinese: "那隻敏捷的棕色狐狸跳過了懶惰的狗。", hint: "一個經典的全字母句" },
        { words: ["Although", "it", "was", "cold", "they", "went", "for", "a", "long", "walk"], chinese: "雖然天氣很冷，他們還是去散了很長的步。", hint: "一個帶有讓步的句子" },
        { words: ["The", "scientist", "discovered", "a", "new", "species", "of", "insect"], chinese: "那位科學家發現了一種新的昆蟲物種。", hint: "一個科學發現" },
        { words: ["She", "has", "been", "practicing", "the", "piano", "for", "many", "years"], chinese: "她已經練習鋼琴很多年了。", hint: "一個持續一段時間的動作" },
        { words: ["The", "old", "library", "contains", "many", "rare", "and", "valuable", "books"], chinese: "這座舊圖書館藏有許多稀有且珍貴的書籍。", hint: "描述一個地方及其內容物" },
        { words: ["He", "was", "surprised", "when", "he", "received", "the", "unexpected", "gift"], chinese: "當他收到意想不到的禮物時，他很驚訝。", hint: "對一個事件的情緒反應" },
        { words: ["Environmental", "protection", "is", "an", "important", "global", "issue"], chinese: "環境保護是一個重要的全球性議題。", hint: "一個全球性的重要議題" },
        { words: ["The", "team", "celebrated", "their", "victory", "after", "the", "championship", "game"], chinese: "在冠軍賽後，隊伍慶祝了他們的勝利。", hint: "一個團體慶祝活動" },
        { words: ["While", "I", "understand", "your", "point", "I", "have", "a", "different", "opinion"], chinese: "雖然我理解你的觀點，但我有不同的意見。", hint: "表達一個對比的看法" },
        { words: ["The", "delicious", "aroma", "of", "baking", "bread", "filled", "the", "entire", "house"], chinese: "烤麵包的美味香氣充滿了整間屋子。", hint: "一個感官描述" },
        { words: ["She", "decided", "to", "pursue", "a", "career", "in", "graphic", "design"], chinese: "她決定從事平面設計的職業。", hint: "一個職業決定" },
        { words: ["The", "ancient", "castle", "stood", "majestically", "on", "top", "of", "the", "hill"], chinese: "那座古老的城堡雄偉地矗立在山頂上。", hint: "一個描述性的歷史句子" },
        { words: ["He", "managed", "to", "solve", "the", "complicated", "puzzle", "by", "himself"], chinese: "他設法自己解決了那個複雜的謎題。", hint: "完成一項困難任務的成就" },
        { words: ["Technology", "has", "dramatically", "changed", "the", "way", "we", "live", "and", "work"], chinese: "科技極大地改變了我們生活和工作的方式。", hint: "科技的影響" },
        { words: ["The", "audience", "applauded", "enthusiastically", "at", "the", "end", "of", "the", "performance"], chinese: "在表演結束時，觀眾熱情地鼓掌。", hint: "對一場表演的反應" },
        { words: ["Despite", "the", "heavy", "rain", "the", "event", "was", "a", "huge", "success"], chinese: "儘管下著大雨，這次活動還是取得了巨大的成功。", hint: "儘管有挑戰仍然成功" },
        { words: ["The", "instructions", "were", "so", "confusing", "that", "nobody", "could", "understand", "them"], chinese: "說明是如此令人困惑，以至於沒有人能理解它們。", hint: "一個因果關係" },
        { words: ["Learning", "a", "new", "language", "requires", "patience", "and", "dedication"], chinese: "學習一門新語言需要耐心和奉獻精神。", hint: "一個關於學習的陳述" },
        { words: ["The", "astronaut", "gazed", "at", "the", "Earth", "from", "the", "space", "station"], chinese: "太空人從太空站凝視著地球。", hint: "一個來自太空的視角" },
        { words: ["Volunteering", "in", "the", "community", "is", "a", "rewarding", "experience"], chinese: "在社區做志工是一次有益的經歷。", hint: "描述一個正面的活動" }
    ],
    6: [
        { words: ["The", "intricate", "design", "of", "the", "cathedral", "attracts", "tourists", "from", "all", "over", "the", "world"], chinese: "大教堂複雜的設計吸引了來自世界各地的遊客。", hint: "描述複雜的建築" },
        { words: ["If", "I", "had", "known", "about", "the", "traffic", "I", "would", "have", "left", "earlier"], chinese: "如果我早知道交通狀況，我就會早點出發。", hint: "一個過去的條件句 (第三條件句)" },
        { words: ["The", "documentary", "provided", "a", "fascinating", "insight", "into", "the", "lives", "of", "deep-sea", "creatures"], chinese: "這部紀錄片對深海生物的生活提供了引人入勝的見解。", hint: "描述一部電影的內容" },
        { words: ["She", "is", "considered", "to", "be", "one", "of", "the", "most", "influential", "artists", "of", "her", "generation"], chinese: "她被認為是她那一代最有影響力的藝術家之一。", hint: "描述一個人的聲譽" },
        { words: ["The", "negotiations", "between", "the", "two", "countries", "were", "both", "long", "and", "complicated"], chinese: "兩國之間的談判既漫長又複雜。", hint: "描述一個政治事件" },
        { words: ["He", "who", "hesitates", "is", "often", "lost", "in", "the", "end"], chinese: "猶豫不決者，最終往往會迷失。", hint: "一句諺語" },
        { words: ["The", "unexpected", "discovery", "revolutionized", "the", "entire", "field", "of", "medicine"], chinese: "這個意想不到的發現徹底改變了整個醫學領域。", hint: "一個發現的影響" },
        { words: ["Despite", "facing", "numerous", "setbacks", "the", "explorer", "persevered", "and", "reached", "his", "destination"], chinese: "儘管面臨無數挫折，探險家仍堅持不懈並到達了目的地。", hint: "克服逆境" },
        { words: ["The", "government", "implemented", "new", "policies", "to", "address", "climate", "change"], chinese: "政府實施了新政策以應對氣候變遷。", hint: "政府對某個議題的行動" },
        { words: ["The", "symphony", "which", "was", "composed", "by", "Mozart", "is", "a", "masterpiece"], chinese: "這首由莫札特譜寫的交響樂是一部傑作。", hint: "一個帶有非限制性子句的句子" },
        { words: ["It", "is", "imperative", "that", "we", "take", "immediate", "action", "to", "protect", "endangered", "species"], chinese: "我們必須立即採取行動保護瀕危物種，這是至關重要的。", hint: "表達緊迫性和重要性" },
        { words: ["The", "evidence", "presented", "in", "court", "was", "not", "sufficient", "to", "secure", "a", "conviction"], chinese: "在法庭上提出的證據不足以定罪。", hint: "一個法律情境" },
        { words: ["The", "ability", "to", "critically", "analyze", "information", "is", "an", "essential", "skill", "in", "the", "modern", "world"], chinese: "批判性地分析資訊的能力是現代世界一項必備的技能。", hint: "描述一項重要技能" },
        { words: ["Never", "before", "had", "she", "witnessed", "such", "a", "breathtaking", "sunset"], chinese: "她以前從未見過如此令人屏息的日落。", hint: "一個用倒裝句來強調的句子" },
        { words: ["The", "organization", "aims", "to", "provide", "humanitarian", "aid", "to", "regions", "affected", "by", "natural", "disasters"], chinese: "該組織旨在向受自然災害影響的地區提供人道主義援助。", hint: "一個組織的使命" },
        { words: ["The", "philosopher", "argued", "that", "happiness", "is", "the", "ultimate", "goal", "of", "human", "existence"], chinese: "那位哲學家認為，幸福是人類存在的最終目標。", hint: "一個哲學論點" },
        { words: ["Had", "he", "invested", "more", "wisely", "he", "would", "not", "be", "in", "this", "financial", "predicament"], chinese: "如果他當初投資得更明智，他現在就不會陷入這種財務困境。", hint: "一個使用倒裝的條件句" },
        { words: ["The", "intricate", "tapestry", "depicted", "a", "historical", "battle", "with", "extraordinary", "detail"], chinese: "那幅複雜的掛毯以非凡的細節描繪了一場歷史性的戰役。", hint: "描述一件藝術品" },
        { words: ["The", "advancements", "in", "artificial", "intelligence", "will", "undoubtedly", "reshape", "numerous", "industries"], chinese: "人工智慧的進步無疑將重塑眾多產業。", hint: "一個關於科技的預測" },
        { words: ["It", "is", "often", "the", "journey", "not", "the", "destination", "that", "truly", "matters"], chinese: "真正重要的往往是過程，而不是目的地。", hint: "一句關於人生的常見說法" }
    ]
};
